Matriks Tensor

1. buat matrix X berukuran 2x3 menggunakan numpy

In [28]:
import numpy as np

In [29]:
x = np.array([[16, 25], [17, 18], [90, 14]])
x

array([[16, 25],
       [17, 18],
       [90, 14]])

In [30]:
# tampilkan ukuran dari matrix X
x.shape

(3, 2)

In [31]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
x[:,0]

array([16, 17, 90])

In [32]:
# tampilkan seluruh elemen dari baris kedua dari matrix X
x[:,1]

array([25, 18, 14])

NO. 2

pytorch

In [33]:
# ulangi soal nomor 1 menggunakan pytorch
import torch

In [34]:
x_pt = torch.tensor([[16, 25], [17, 18], [90, 14]])
x_pt

tensor([[16, 25],
        [17, 18],
        [90, 14]])

In [35]:
x_pt.shape

torch.Size([3, 2])

In [36]:
x_pt[0,:]

tensor([16, 25])

In [37]:
x_pt[1,:]

tensor([17, 18])

tensorflow

In [38]:
# ulangi soal nomor 1 menggunakan tensorflow
import tensorflow as tf

In [39]:
x_tf = tf.Variable([[16, 25], [17, 18], [90, 14]])
x_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[16, 25],
       [17, 18],
       [90, 14]], dtype=int32)>

In [40]:
tf.shape(x_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>

In [41]:
x_tf[0,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([16, 25], dtype=int32)>

In [42]:
x_tf[1,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([17, 18], dtype=int32)>