In [38]:
# 1. buat vector x dengan ukuran 3x1
import numpy as np


In [39]:
x = np.array([12,13,14])
x

array([12, 13, 14])

In [40]:
# hitung panjang vector x
len(x)

3

In [41]:
#tampilkan ukuran vector x
x.shape

(3,)

In [42]:
# tampilkan tipe data dari vector x
type(x)

numpy.ndarray

In [43]:
# akses elemen pertama dari vector x
x[0]

np.int64(12)

In [44]:
# tampilkan tipe data elemen pertama dari vector x
type(x[0])

numpy.int64

In [45]:
# 2. lakukan transpose pada vector x dan simpan pada variabel x_t
x_t = x.T
x_t

array([12, 13, 14])

In [46]:
# tampilkan ukuran dari vector x_t
x_t.shape

(3,)

In [47]:
# lakukan transpose pada vector y dan simpan pada variabel y_t
y = np.array([34,45,56])
y_t = y.T
y_t

array([34, 45, 56])

In [48]:
# tampilkan ukuran dari vector x_t
x_t.shape

(3,)

In [49]:
# lakukan soal nomor 2 menggunakan pytorch dan tensorflow
import torch
import tensorflow as tf

In [50]:
x_pt = torch.tensor([12,13,14])
x_pt


tensor([12, 13, 14])

In [52]:
x_tf = tf.Variable([12,13,14])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([12, 13, 14], dtype=int32)>